#nullable enable
using Microsoft.Dafny;
using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static DafnyCore.IncrementalCompilation.ProtectorFunctions;

namespace DafnyCore.IncrementalCompilation {
  internal static class ProtectedExtension { // FOR THE LOVE OF GOD LET'S KEEP THIS BEFORE THE RESOLUTION
    public static Expression AsProtected(this Expression e) => e switch {
      ApplyExpr p => AsProtectedParticular(p),
      FunctionCallExpr p => AsProtectedParticular(p),
      MemberSelectExpr p => AsProtectedParticular(p),
      MultiSelectExpr p => AsProtectedParticular(p),
      SeqSelectExpr p => AsProtectedParticular(p),
      ThisExpr p => p switch {
        ImplicitThisExpr pp => pp switch {
          ImplicitThisExprConstructorCall ppp => AsProtectedParticular(ppp),
          _ => AsProtectedParticular(pp),
        },
        _ => AsProtectedParticular(p),
      },
      DisplayExpression p => p switch {
        SeqDisplayExpr pp => AsProtectedParticular(pp),
        SetDisplayExpr pp => AsProtectedParticular(pp),
        MultiSetDisplayExpr pp => AsProtectedParticular(pp),
        _ => AsProtectedParticular(p),
      },
      MapDisplayExpr p => AsProtectedParticular(p),
      MultiSetFormingExpr p => AsProtectedParticular(p),
      SeqConstructionExpr p => AsProtectedParticular(p),
      SeqUpdateExpr p => AsProtectedParticular(p),
      ComprehensionExpr p => p switch {
        LambdaExpr pp => AsProtectedParticular(pp),
        MapComprehension pp => AsProtectedParticular(pp),
        QuantifierExpr pp => pp switch {
          ForallExpr ppp => AsProtectedParticular(ppp),
          ExistsExpr ppp => AsProtectedParticular(ppp),
          _ => AsProtectedParticular(pp),
        },
        SetComprehension pp => AsProtectedParticular(pp),
        _ => AsProtectedParticular(p),
      },
      ITEExpr p => AsProtectedParticular(p),
      NestedMatchExpr p => AsProtectedParticular(p),
      TernaryExpr p => AsProtectedParticular(p),
      DatatypeValue p => AsProtectedParticular(p),
      FieldLocation p => AsProtectedParticular(p),
      IndexFieldLocation p => AsProtectedParticular(p),
      LocalsObjectExpression p => AsProtectedParticular(p),
      OldExpr p => AsProtectedParticular(p),
      UnchangedExpr p => AsProtectedParticular(p),
      WildcardExpr p => AsProtectedParticular(p),
      BinaryExpr p => AsProtectedParticular(p),
      DecreasesToExpr p => AsProtectedParticular(p),
      UnaryExpr p => p switch {
        UnaryOpExpr pp => pp switch {
          FreshExpr ppp => AsProtectedParticular(ppp),
          _ => AsProtectedParticular(pp),
        },
        TypeUnaryExpr pp => pp switch {
          ConversionExpr ppp => AsProtectedParticular(ppp),
          TypeTestExpr ppp => AsProtectedParticular(ppp),
          _ => AsProtectedParticular(pp),
        },
        _ => AsProtectedParticular(p),
      },
      BoxingCastExpr p => AsProtectedParticular(p),
      UnboxingCastExpr p => AsProtectedParticular(p),
      IdentifierExpr p => p switch {
        AutoGhostIdentifierExpr pp => AsProtectedParticular(pp),
        ImplicitIdentifierExpr pp => AsProtectedParticular(pp),
        _ => AsProtectedParticular(p),
      },
      LetExpr p => p switch {
        BoogieGenerator.SubstLetExpr pp => AsProtectedParticular(pp),
        _ => AsProtectedParticular(p),
      },
      ResolverIdentifierExpr p => AsProtectedParticular(p),
      ConcreteSyntaxExpression p => p switch {
        NameSegment pp => AsProtectedParticular(pp),
        SuffixExpr pp => pp switch {
          ApplySuffix ppp => ppp switch {
            ProtectToProveApplySuffix pppp => AsProtectedParticular(pppp),
            _ => AsProtectedParticular(ppp),
          },
          ExprDotName ppp => AsProtectedParticular(ppp),
          FieldLocationExpression ppp => AsProtectedParticular(ppp),
          IndexFieldLocationExpression ppp => AsProtectedParticular(ppp),
          _ => AsProtectedParticular(pp),
        },
        DatatypeUpdateExpr pp => AsProtectedParticular(pp),
        ChainingExpression pp => AsProtectedParticular(pp),
        ParensExpression pp => pp switch {
          AutoGeneratedExpression ppp => AsProtectedParticular(ppp),
          _ => AsProtectedParticular(pp),
        },
        LetOrFailExpr pp => AsProtectedParticular(pp),
        DefaultValueExpression pp => pp switch { // geniunely unreachable???
          DefaultValueExpressionType ppp => AsProtectedParticular(ppp),
          DefaultValueExpressionPreType ppp => AsProtectedParticular(ppp),
          _ => AsProtectedParticular(pp),
        },
        NegationExpression pp => AsProtectedParticular(pp),
        _ => AsProtectedParticular(p),
      },
      LiteralExpr p => p switch {
        StaticReceiverExpr pp => AsProtectedParticular(pp),
        CharLiteralExpr pp => AsProtectedParticular(pp),
        StringLiteralExpr pp => AsProtectedParticular(pp),
        _ => AsProtectedParticular(p),
      },
      StmtExpr p => AsProtectedParticular(p),
      MatchExpr p => AsProtectedParticular(p),
      BoogieGenerator.BoogieWrapper p => AsProtectedParticular(p),
      BoogieGenerator.BoogieFunctionCall p => AsProtectedParticular(p),
      _ => AsProtectedParticular(e),
    };
    private static Cloner cloner { get; } = new();
    private static E Clone<E>(this ICloneable<E> e) => e.Clone(cloner);
    private static Expression NotImplemented(Expression e) {
      Console.WriteLine($"Dafny IPM: {e.GetType().Name} not yet implemented.");
      return e;
    }
    private static Expression AsProtectedParticular(Expression e) => NotImplemented(e);
    private static Expression AsProtectedParticular(StaticReceiverExpr e) => e.Clone<StaticReceiverExpr>();
    private static Expression AsProtectedParticular(LiteralExpr e) => e.Clone();
    private static Expression AsProtectedParticular(ProtectToProveApplySuffix e) => e; // no need to make a clone, since they're another kind of protection that also clones its original
    private static Expression AsProtectedParticular(ThisExpr e) => ProtectorFunctions.WrappedWith(e.Clone(), Protect);
    private static Expression AsProtectedParticular(IdentifierExpr e) => ProtectorFunctions.WrappedWith(e.Clone(), Protect);
    private static Expression AsProtectedParticular(DatatypeValue e) => ProtectorFunctions.WrappedWith(e.Clone(), Protect);
    private static Expression AsProtectedParticular(NameSegment e) => ProtectorFunctions.WrappedWith(e.Clone(), Protect);
    private static Expression AsProtectedParticular(UnaryOpExpr e) {
      // `UnaryOpExpr.Opcode.Lit` used in translation, this method is called before translation
      Contract.Assert(e.Op is not UnaryOpExpr.Opcode.Lit);
      Contract.Assert(e.Op is UnaryOpExpr.Opcode.Not or
        UnaryOpExpr.Opcode.Cardinality or
        UnaryOpExpr.Opcode.Allocated or
        UnaryOpExpr.Opcode.Assigned || e is FreshExpr { Op: UnaryOpExpr.Opcode.Fresh });
      return new UnaryOpExpr(e.Origin, e.Op, e.E.AsProtected());
    }
    private static Expression AsProtectedParticular(SeqSelectExpr e) => new SeqSelectExpr(
      e.Origin, e.SelectOne, e.Seq.AsProtected(), e.E0.ApplyIfNotNull(AsProtected), e.E1.ApplyIfNotNull(AsProtected), e.CloseParen
    );
    private static Expression AsProtectedParticular(SeqDisplayExpr e) => new SeqDisplayExpr(e.Origin, e.Elements.ConvertAll(AsProtected));
    private static Expression AsProtectedParticular(SetDisplayExpr e) => new SetDisplayExpr(e.Origin, e.Finite, e.Elements.ConvertAll(AsProtected));
    private static Expression AsProtectedParticular(MultiSetDisplayExpr e) => new MultiSetDisplayExpr(e.Origin, e.Elements.ConvertAll(AsProtected));
    private static Expression AsProtectedParticular(MapDisplayExpr e) => new MapDisplayExpr(
      e.Origin, e.Finite, e.Elements.ConvertAll(entry => new MapDisplayEntry(entry.A.AsProtected(), entry.B.AsProtected()))
    );
    private static Expression AsProtectedParticular(SeqConstructionExpr e) => new SeqConstructionExpr(
      e.Origin, e.ExplicitElementType.ApplyIfNotNull(cloner.CloneType), e.N.AsProtected(), e.Initializer.AsProtected()
    );
    private static Expression AsProtectedParticular(SeqUpdateExpr e) => new SeqUpdateExpr(e.Origin, e.Seq.AsProtected(), e.Index.AsProtected(), e.Value.AsProtected());
    private static Expression AsProtectedParticular(BinaryExpr e) => new BinaryExpr(e.Origin, e.Op, e.E0.AsProtected(), e.E1.AsProtected());
    private static Expression AsProtectedParticular(ChainingExpression e) {
      if (e.PrefixLimits.Any(l => l is not null)) { // why?
        return NotImplemented(e);
      }
      return new ChainingExpression(e.Origin, e.Operands.ConvertAll(AsProtected), e.Operators, e.OperatorLocs, e.PrefixLimits);
    }
    private static Expression AsProtectedParticular(ParensExpression e) => new ParensExpression(e.Origin, e.E.AsProtected());
    private static Expression AsProtectedParticular(DefaultValueExpression e) {
      Contract.Assert(e.WasResolved());
      Contract.Assert(e.Resolved is not null);
      return NotImplemented(e);
    }
    private static Expression AsProtectedParticular(LetExpr e) => new LetExpr(
      e.Origin, e.LHSs.ConvertAll(cloner.CloneCasePattern), e.RHSs.ConvertAll(AsProtected), e.Body.AsProtected(), e.Exact, cloner.CloneAttributes(e.Attributes)
    );
    private static Expression AsProtectedParticular(ApplySuffix e) => new ApplySuffix(
      e.Origin, e.AtTok, e.Lhs, e.Bindings.ArgumentBindings.ConvertAll(ab => new ActualBinding(ab.FormalParameterName, ab.Actual.AsProtected(), ab.IsGhost)), e.CloseParen
    );
    private static Expression AsProtectedParticular(StmtExpr e) {
      Statement ReplaceExprInStatement(Statement s) => s switch { // TODO: complete everything here, only PredicateStmt is handled properly
        PredicateStmt stmt => stmt switch {
          AssertStmt assert => new AssertStmt(assert.Origin, assert.Expr.AsProtected(), assert.Label is null ? null : new AssertLabel(assert.Label.Tok, assert.Label.Name), cloner.CloneAttributes(assert.Attributes)),
          AssumeStmt assume => new AssumeStmt(assume.Origin, assume.Expr.AsProtected(), cloner.CloneAttributes(assume.Attributes)),
          ExpectStmt expect => new ExpectStmt(expect.Origin, expect.Expr.AsProtected(), cloner.CloneExpr(expect.Message), cloner.CloneAttributes(expect.Attributes)), // Protect `expect.Message`?
          _ => throw new Cce.UnreachableException(),
        },
        CalcStmt stmt => stmt,
        ForallStmt stmt => stmt,     // one could wrap a `forall` expression around the `ensures` clause, but "true" is conservative and much simpler :)
        HideRevealStmt stmt => stmt, // one could use the definition axiom or the referenced labeled assertions, but "true" is conservative and much simpler :)
        AssignStatement stmt => stmt,// one could use the postcondition of the method, suitably instantiated, but "true" is conservative and much simpler :)
        BlockByProofStmt stmt => stmt,
        _ => throw new Cce.UnreachableException(),  // unexpected statement
      };
      return new StmtExpr(e.Origin, ReplaceExprInStatement(e.S), e.E.AsProtected());
    }
  }
}
